[package]
name = "zynq7000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
armv7a = { git = "https://github.com/moritz-meier/armv7a.git" }
critical-section = "1.1.2"
fdt = { workspace = true }
tock-registers = { workspace = true }
